name: Release

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          TSL_COOKIE: ${{ secrets.TSL_COOKIE }}

      - name: Remove index.html
        run: |
          rm -f index.html
          git config --global user.name 'andrewcrobertson'
          git config --global user.email 'andrewcrobertson@users.noreply.github.com'
          git add -A
          git commit -am "chore: remove index.html"
          git push

      - name: Copy/Commit index.html
        run: |
          mv new.html index.html
          git config --global user.name 'andrewcrobertson'
          git config --global user.email 'andrewcrobertson@users.noreply.github.com'
          git add -A
          git commit -m "chore: update index.html"
          git push
